.PHONY: clean All

All:
	@echo "----------Building project:[ ssh-keygen - Debug ]----------"
	@cd "ssh-keygen" && "$(MAKE)" -f  "ssh-keygen.mk"
clean:
	@echo "----------Cleaning project:[ ssh-keygen - Debug ]----------"
	@cd "ssh-keygen" && "$(MAKE)" -f  "ssh-keygen.mk" clean
